#############################################################################
# Makefile for building: Election
# Generated by qmake (2.01a) (Qt 4.8.7) on: dim. janv. 22 13:56:26 2017
# Project:  Election.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile Election.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = bulletin.cpp \
		candidat.cpp \
		data.cpp \
		main.cpp \
		Mainwindow.cpp \
		qcustomplot.cpp \
		resultwindow.cpp moc_Mainwindow.cpp \
		moc_qcustomplot.cpp \
		moc_resultwindow.cpp
OBJECTS       = bulletin.o \
		candidat.o \
		data.o \
		main.o \
		Mainwindow.o \
		qcustomplot.o \
		resultwindow.o \
		moc_Mainwindow.o \
		moc_qcustomplot.o \
		moc_resultwindow.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Election.pro
QMAKE_TARGET  = Election
DESTDIR       = 
TARGET        = Election

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_Mainwindow.h ui_resultwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Election.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Election.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Election.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Election1.0.0 || $(MKDIR) .tmp/Election1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Election1.0.0/ && $(COPY_FILE) --parents bulletin.h candidat.h data.h Mainwindow.h qcustomplot.h resultwindow.h .tmp/Election1.0.0/ && $(COPY_FILE) --parents bulletin.cpp candidat.cpp data.cpp main.cpp Mainwindow.cpp qcustomplot.cpp resultwindow.cpp .tmp/Election1.0.0/ && $(COPY_FILE) --parents Mainwindow.ui resultwindow.ui .tmp/Election1.0.0/ && (cd `dirname .tmp/Election1.0.0` && $(TAR) Election1.0.0.tar Election1.0.0 && $(COMPRESS) Election1.0.0.tar) && $(MOVE) `dirname .tmp/Election1.0.0`/Election1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Election1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_Mainwindow.cpp moc_qcustomplot.cpp moc_resultwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Mainwindow.cpp moc_qcustomplot.cpp moc_resultwindow.cpp
moc_Mainwindow.cpp: resultwindow.h \
		data.h \
		bulletin.h \
		candidat.h \
		Mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) Mainwindow.h -o moc_Mainwindow.cpp

moc_qcustomplot.cpp: qcustomplot.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) qcustomplot.h -o moc_qcustomplot.cpp

moc_resultwindow.cpp: data.h \
		bulletin.h \
		candidat.h \
		resultwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) resultwindow.h -o moc_resultwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_Mainwindow.h ui_resultwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_resultwindow.h
ui_Mainwindow.h: Mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic Mainwindow.ui -o ui_Mainwindow.h

ui_resultwindow.h: resultwindow.ui \
		qcustomplot.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic resultwindow.ui -o ui_resultwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

bulletin.o: bulletin.cpp bulletin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bulletin.o bulletin.cpp

candidat.o: candidat.cpp candidat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o candidat.o candidat.cpp

data.o: data.cpp data.h \
		bulletin.h \
		candidat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o data.o data.cpp

main.o: main.cpp Mainwindow.h \
		resultwindow.h \
		data.h \
		bulletin.h \
		candidat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Mainwindow.o: Mainwindow.cpp Mainwindow.h \
		resultwindow.h \
		data.h \
		bulletin.h \
		candidat.h \
		ui_Mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Mainwindow.o Mainwindow.cpp

qcustomplot.o: qcustomplot.cpp qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcustomplot.o qcustomplot.cpp

resultwindow.o: resultwindow.cpp resultwindow.h \
		data.h \
		bulletin.h \
		candidat.h \
		ui_resultwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o resultwindow.o resultwindow.cpp

moc_Mainwindow.o: moc_Mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Mainwindow.o moc_Mainwindow.cpp

moc_qcustomplot.o: moc_qcustomplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustomplot.o moc_qcustomplot.cpp

moc_resultwindow.o: moc_resultwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_resultwindow.o moc_resultwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

